my:
  greeting: Hello
  list:
    values: One,Two,Three

app:
  name: My app
  description: Welcome to ${app.name}

dbValues: "{connectionString: 'http://__', userName: 'foo', password: 'pass'}"

db:
  connection: "{connection: 'http://__', userName: 'foo', password: 'pass'}"
  host: 127.0.0.1
  port: 1200

management.endpoints.web.exposure.include: "*"

# spring.profiles.active: test